### ISSUE TITLE
Wrong compiling

### ISSUE THREAD

**Issue by iodimitrov** [golang-enthusiast/app-yaml-env-compiler#1]
Hello,

I have issue with env variables that are not secrets. For example:

```yaml
DB_NAME: $DB_NAME
DB_HOST: $DB_HOST
DB_DRIVER: 'mysql'
```
got compiled to:

```yaml
DB_NAME: (my secret)
DB_HOST: (my secret)
DB_DRIVER:
```

In this case DB_DRIVER is not a secret and got wiped out. Is it expected behavior?
