### ISSUE TITLE
Set specific path to custom app.yaml file?

### ISSUE THREAD

**Issue by basickarl** [golang-enthusiast/app-yaml-env-compiler#2]
Hi! Would it be possible to set a specific path to custom app.yaml file? We have two app.yaml files which are used in different contexts!

**Comment by dovidio** [comment]
I've added the possibility to configure the path in my fork: https://github.com/dovidio/app-yaml-env-compiler
You can use my action meanwhile, e.g.:
```yaml
        uses: dovidio/app-yaml-env-compiler@master
        env:
          DB_URL: ${{ secrets.CLOUD_SQL_JDBC_URL }}
        with:
          appyamlpath: './src/main/appengine/app.yaml'
```
